import './globals.css'
import { Inter, Montserrat, Roboto } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat',
  display: 'swap',
  weight: ['400', '700']
})
const roboto = Roboto({
  subsets: ['latin'],
  variable: '--font-roboto',
  display: 'swap',
  weight: ['400', '700']
})

export const metadata = {
  title: 'Cesar Sample Website',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en"  className={`${montserrat.variable}  ${roboto.variable}`}>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
